### ISSUE TITLE
configuring-hive-metastore.md password

### ISSUE THREAD

**Issue by kfox1111** [kube-reporting/metering-operator#1065]
configuring-hive-metastore.md mentions putting the mysql password in the spec. Is there a way to put it in a secret instead? If not, please consider this a feature request.

**Comment by timflannagan1** [comment]
It doesn't look like that's possible at the moment:
```yaml
{{- if .Values.hive.spec.config.db.password }}
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>{{ .Values.hive.spec.config.db.password }}</value>
      </property>
{{- end }}
```

I can look more into this, but my attention is dealing with 4.3 bugs at the moment.

**Comment by timflannagan1** [comment]
I still have this on the backlog, but it won't get tackled until the next release cycle (4.5).

**Comment by timflannagan1** [comment]
This functionality was added recently to the release-4.6 branch - closing.
