### ISSUE TITLE
[question] multi arch support for metering

### ISSUE THREAD

**Issue by jichenjc** [kube-reporting/metering-operator#1103]
question on whether there is a plan to support multiarch eg. IBM s390x or power （ARM etc) later on? as currently the released image is not multi arch (quay.io only has x86 version) or this is something that need to be done downstream but some enhancement on the build script in this repo? 

Also, operator-metering depends on other projects like hive as well, will check whether need some update there as well... thanks

**Comment by timflannagan1** [comment]
There's a multi-arch epic on the backlog but I haven't reached out to the multi-arch team here at Red Hat. As far as I understand, there's definitely known problems with Hadoop, and potentially the Presto and Hive forks.

**Comment by jichenjc** [comment]
OK, I will search the backlog and if you can help to share the backlog link ?
I understand the dependency to hadoop and Presto  / Hive, so you are saying there are known issues in Hadoop side, I might need check this link if you can provide us the link as well, 

thanks a lot for the info

**Comment by timflannagan1** [comment]
I was just regurgitating what was listed in the actual epic [1] and I haven't investigated the compatibility of the actual components.

[1] https://issues.redhat.com/browse/MC-671

**Comment by jichenjc** [comment]
I used my account to access the issue you mentioned but no lucky, I can't open the link..

**Comment by timflannagan1** [comment]
Apologies for the real slow replies. Red Hat has decided to deprecate the Metering project in the Openshift 4.6 release cycle, and so the current team likely won't tackle any multi-arch support for this project.
