### ISSUE TITLE
Init script for postgres and potential to expand to other alternative dbs.

### ISSUE THREAD

**Issue by EmilyM1** [kube-reporting/metering-operator#1423]
I wrote a handy little bash script.
I've been refining it while I work on the Postgres bug. Essentially I have automated everything from secrets to injected exposed service route into the Metering CR.
Opening issue so that we can have discussion on how/where to add this shell script if Postgres and Metering seem to be compatible. It can be easily modded to use Mysql as well.

**Comment by bentito** [comment]
@EmilyM1 can you provide link to the script, like in a gist?

**Comment by timflannagan1** [comment]
@EmilyM1 Just following up on Brett's previous comment. Can we either paste that script in a comment or link to a gist so we can close this issue out?
