### ISSUE TITLE
[question] Is there a component that can replace presto？

### ISSUE THREAD

**Issue by xkwangcn** [kube-reporting/metering-operator#1433]
Hi, all

Presto is not supported on my architecture. If presto is not used, is there any other solution for metering?

Thanks for your help and reply.

**Comment by bentito** [comment]
Hi @xkwangcn ,
Presto is installed by default and managed by the Metering Operator and is a core component that it can't work without. You can choose different backing stores for Presto via Hive/Hadoop, such as HDFS (with Derby being used behind the scenes as the default SQL engine), or MySQL or Postgresql, but you can't avoid Presto in the current form of the operator.

**Comment by xkwangcn** [comment]
Hi @bentito ,
Thanks for your reply.
Helpful information, thank you. 
And I have another question:
Does Hadoop or Hive have components that can be replaced? Hadoop and hive are also not sure if supported on my platform.

**Comment by bentito** [comment]
Hi @xkwangcn, If I am understanding your question correctly... Hadoop and Hive could certainly be compiled from more minimal sets than the current images in use in Metering, but it's a very time consuming endeavor to create a minimal custom build of these interlocked components. It's especially hard to maintain a minimal custom build over time. Because of this, we don't necessarily try to cut out all the subcomponents of either Hadoop or Hive in our image builds. We do specifically have an inclusion set for each, but it's pretty broad and covers most of the subcomponents of each.

**Comment by xkwangcn** [comment]
Hi，@bentito Thanks for your reply, my last statement was not clear enough. 
But in fact, I just want to know, if there is no Hadoop and hive, is there any other working solution for metering? 
If you can avoid hadoop and hive, what is the specific solution?

My current problem is that I am not sure whether hadoop and hive are supported in my platform.

**Comment by timflannagan1** [comment]
@xkwangcn Unfortunately no, the only implementation in place is the Hive and Presto combination, and just to comment further, you won't see any multi-architecture effort, at least from Red Hat, done upstream with this project either so I would recommend looking elsewhere for your cluster reporting needs. In general, the effort to swap out Hive and Presto in favor of something like Postgres or Mysql acting as both of the storage and query layer is too large for the team to consider at the moment.

**Comment by xkwangcn** [comment]
Hi, @timflannagan1 OK, thank you very much. 
My work platform is s390x, does metering have plans to support s390x?

**Comment by timflannagan1** [comment]
@xkwangcn We previously had an epic tracking multi-architecture support, but we have recently paused (likely forever) that work.

**Comment by xkwangcn** [comment]
@timflannagan1 okay, seems forever, thanks for your information.

**Comment by timflannagan1** [comment]
@xkwangcn Yeah, no problem. I'm going to close this issue out in the meantime. Feel free to continue opening additional ones for any questions you may have.
