### ISSUE TITLE
[Question]The Metering Operator is deprecated in OCP4.6.  Is there any alternative?

### ISSUE THREAD

**Issue by dotw** [kube-reporting/metering-operator#1438]
Openshift 4.6 has deprecated `Metering Operator`. 
Is there any alternative? or we just want to remove the whole metering features from OCP in the future?

> 1.4.1.3. Metering Operator
The Metering Operator is deprecated and will be removed in a future release.

**Comment by timflannagan1** [comment]
The closest alternative is [Cost Management](https://github.com/project-koku), but you may need to wait for their next release as they're currently working on building up their internal APIs to directly query Prometheus. Note: that in-cluster data is sent to cloud.redhat.com so if that's fine in your own internal environment, I would give it a try. CC @chargio

**Comment by timflannagan1** [comment]
Just circling back to this, the alternatives are either continue to use metering until it's removal (likely around the 4.9 or 4.10 timeline), emulate some of the functionality that metering provides by directly querying Prometheus for the queries you care about, or wait until the next release of Cost Management that removes the metering dependency.
