### ISSUE TITLE
Development of metering-operator

### ISSUE THREAD

**Issue by amalkurup89** [kube-reporting/metering-operator#1518]
@timflannagan Any specific reason on stopping the active development here

**Comment by timflannagan** [comment]
@amalkurup89 Take a look at Sergio's (PM for the project) response to a similar question here: https://github.com/kube-reporting/metering-operator/issues/1460#issuecomment-742683117.

**Comment by timflannagan** [comment]
I'm going to close this out. Let me know if you need any more context around the decision.

/close
